INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('001','BANCO DO BRASIL AS');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('003','BANCO DA AMAZONIA SA');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('004','BANCO DO NORDESTE DO BRASIL SA');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('008','BANCO SANTANDER MERIDIONAL SA');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('021','BANCO DO ESTADO DO ESPIRITO SANTO SA');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('024','BANCO DO ESTADO DE PERNAMBUCO SA');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('025','BANCO ALFA S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('027','BANCO DO ESTADO DE SANTA CATARINA S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('033','BANCO DO ESTADO DE SAO PAULO S.A.');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('041','BANCO DO ESTADO DO RIO GRANDE DO SUL S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('044','BANCO BVA S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('047','BANCO DO ESTADO DE SERGIPE S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('069','BPN BRASIL BANCO MULTIPLO S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('070','BANCO DE BRASILIA S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('074','BANCO J. SAFRA S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('104','CAIXA ECONOMICA FEDERAL S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('107','BANCO BBM S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('151','NOSSA CAIXA - NOSSO BANCO S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('224','BANCO FIBRA S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('237','BANCO BRADESCO S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('246','BANCO ABC BRASIL S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('263','BANCO CACIQUE S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('266','BANCO CEDULA S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('320','BANCO INDL E COML S/A - BICBANCO');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('341','BANCO ITAU S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('346','BFB   LEASING S/A ');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('347','BANCO SUDAMERIS BRASIL S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('353','BANCO SANTANDER BRASIL S/A.');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('356','BANCO ABN AMRO S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('389','BANCO MERCANTIL DO BRASIL S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('394','BANCO BMC S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('399','HSBC BANK BRASIL S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('409','BANCO UNIBANCO S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('422','BANCO SAFRA S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('453','BANCO RURAL S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('479','BANKBOSTON BCO MULTIPLO S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('600','BANCO LUSO BRASILEIRO S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('604','BANCO INDUSTRIAL DO BRASIL S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('611','BANCO PAULISTA S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('623','BANCO PANAMERICANO S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('633','BANCO RENDIMENTO S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('634','BANCO TRIBANCO');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('637','BANCO SOFISA S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('643','BANCO PINE S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('653','BANCO INDUSVAL S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('655','BANCO VOTORANTIM S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('707','BANCO DAYCOVAL S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('719','BANCO BANIF PRIMUS S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('721','BANCO CREDIBEL S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('734','BANCO GERDAU S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('738','BANCO MORADA S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('739','BANCO GALVAO DE NEGOCIOS S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('741','BANCO RIBEIRAO PRETO S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('745','BANCO CITIBANK S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('748','BANCO COOPERATIVO SICREDI S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('749','BR BANCO MERCANTIL S/A');
INSERT INTO BANCO(codigoBanco, descricaoBanco) VALUES ('756','BANCO COOPERATIVO DO BRASIL S/A');